version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "NETWICHER@2025@DB!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - sqlserver_network
    command: >
      /bin/bash -c "echo 'Setting up SQL Server...' &&
      /opt/mssql/bin/sqlservr"
    deploy:
      resources:
        limits:
          memory: 2GB

networks:
  sqlserver_network:
    driver: bridge
